version: '3'
services:
  gogs:
    image: gogs/gogs
    # 映射真机 2223 到 gogs 的 22 端口，用于 git@ 克隆
    # 映射真机 8003 到 gogs 的 3000 端口，使用 localhost:8003 访问，自行添加nginx代理即可
    ports:
      - "2223:22"
      - "8003:3000"
    volumes:
      - ./gogs-data:/data
    networks:
      - drone
  drone-server:
    image: drone/drone:1.0.0-rc.4
    # 映射真机 8002 到 drone 的80端口，使用 localhost:8002 访问，自行添加nginx代理即可
    ports:
      - 8002:80
    environment:
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      # change this，不带 http[s]:// 的网址路径
      - DRONE_SERVER_HOST=drone.example.com
      # change this，这个要带 http[s]:// 的网址路径
      - DRONE_GOGS_SERVER=http://gogs.example.com
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=your_random_secret
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone-data:/data
    restart: always
  drone:
    image: drone/agent:1.0.0-rc.4
    environment:
      - DRONE_RPC_SERVER=drone-server:80
      - DRONE_RPC_SECRET=your_random_secret
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
networks:
  drone:
    driver: bridge