version: '3'
services:
  gogs:
    image: gogs/gogs
    ports:
      - "2223:22"
      - "89:3000"
    volumes:
      - ./gogs-data:/data
    networks:
      - drone
  drone-server:
    image: drone/drone:1.0.0-rc.4
    ports:
      - 8002:80
    environment:
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      # change this
      - DRONE_SERVER_HOST=http://drone.com
      # change this
      - DRONE_GOGS_SERVER=http://gogs.com
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=your_random_secret
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone-data:/data
    restart: always
  drone-agent:
    image: drone/agent:1.0.0-rc.4
    environment:
      - DRONE_RPC_SERVER=drone-server:80
      - DRONE_RPC_SECRET=your_random_secret
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
networks:
  drone:
    driver: bridge