version: '3'
services:
  gogs:
    image: gogs/gogs
    # 映射真机 2223 到 gogs 的 22 端口，用于 git@ 克隆
    # 映射真机 8003 到 gogs 的 3000 端口，使用 服务器IP:8003 访问，自行添加nginx代理即可
    ports:
      - "2223:22"
      - "8003:3000"
    volumes:
      - ./gogs-data:/data
    networks:
      - drone
    restart: always
  drone-server:
    image: drone/drone
    # 映射真机 8002 到 drone 的80端口，使用 服务器IP:8002 访问，自行添加nginx代理即可
    ports:
      - 8002:80
    environment:
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      # change this，不带 http[s]:// 的网址路径
      - DRONE_SERVER_HOST=drone.example.com
      # 如果是gogs，就改这一行，这个要带 http[s]:// 的网址路径
      - DRONE_GOGS_SERVER=http://gogs.example.com
      # 如果是github，就改这里，自己去 github 里面新建APP，得到这两个参数
      - DRONE_GITHUB_CLIENT_ID=
      - DRONE_GITHUB_CLIENT_SECRET=
      # 控制只能这个 github 用户可以授权，多个用英文逗号分隔，不然会造成所有人都可以用
      - DRONE_USER_FILTER=GITHUB用户名
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=your_random_secret
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone-data:/data
    restart: always
  drone-runner:
    image: drone/drone-runner-docker
    environment:
      - DRONE_RPC_SERVER=drone-server:80
      - DRONE_RPC_SECRET=your_random_secret
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_HOST=drone-server:80
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
networks:
  drone:
    driver: bridge
